### ISSUE TITLE
build: push docker image to docker hub

### ISSUE THREAD

**Issue by jonathanwalter** [Eyevinn/autovmaf-api#40]
Since this project has been open sourced, we should push the docker image to Docker Hub and not (only) to our internal container registry in AWS.

This will make it much easier to use outside of ECS, since we don't have to mess around with ECRs weird way of doing authentication.

`docker-compose.yml` should be updated to reflect this change.

This:
https://github.com/Eyevinn/autovmaf-api/blob/6de56d758dfc3cc36e85d29dc4b4502f382a8008/docker-compose.yml#L6-L10

Would become something like:
```yaml
services:
  autoabr-api:
    image: eyevinntechnology/autoabr-api
```
